//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_control_comercio.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public System.Guid employee_id { get; set; }
        public Nullable<int> employee_dni { get; set; }
        public string employee_name { get; set; }
        public string employee_lastname { get; set; }
        public string employee_address { get; set; }
        public Nullable<int> employee_cellphone { get; set; }
        public Nullable<System.Guid> physical_location_id { get; set; }
        public Nullable<bool> enable { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
    }
}
