//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_control_comercio.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class logs
    {
        public System.Guid log_id { get; set; }
        public string log_type { get; set; }
        public string log_detail { get; set; }
        public Nullable<System.Guid> physical_location_id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
    }
}
