//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_control_comercio.Models.BD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistema_control_comercio : DbContext
    {
        public sistema_control_comercio()
            : base("name=sistema_control_comercio")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<employee> employee { get; set; }
        public virtual DbSet<inventary> inventary { get; set; }
        public virtual DbSet<payment_method> payment_method { get; set; }
        public virtual DbSet<payment_service> payment_service { get; set; }
        public virtual DbSet<payment_suppliers> payment_suppliers { get; set; }
        public virtual DbSet<payment_suppliers_order> payment_suppliers_order { get; set; }
        public virtual DbSet<permission> permission { get; set; }
        public virtual DbSet<physical_location> physical_location { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_rawmaterial> product_rawmaterial { get; set; }
        public virtual DbSet<profile> profile { get; set; }
        public virtual DbSet<profile_permission> profile_permission { get; set; }
        public virtual DbSet<profile_profile> profile_profile { get; set; }
        public virtual DbSet<raw_material> raw_material { get; set; }
        public virtual DbSet<sale> sale { get; set; }
        public virtual DbSet<sale_order> sale_order { get; set; }
        public virtual DbSet<service> service { get; set; }
        public virtual DbSet<supplier> supplier { get; set; }
        public virtual DbSet<unit_of_measurement> unit_of_measurement { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<user_permission> user_permission { get; set; }
        public virtual DbSet<user_profile> user_profile { get; set; }
    }
}
