//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api_control_comercio.Models.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.product_rawmaterial = new HashSet<product_rawmaterial>();
            this.sale_order = new HashSet<sale_order>();
        }
    
        public System.Guid product_id { get; set; }
        public string product_code { get; set; }
        public string product_name { get; set; }
        public Nullable<int> product_cost { get; set; }
        public Nullable<int> product_price { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
        public Nullable<System.Guid> physical_location_id { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public Nullable<System.DateTime> modification_date { get; set; }
    
        public virtual category category { get; set; }
        public virtual physical_location physical_location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_rawmaterial> product_rawmaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sale_order> sale_order { get; set; }
    }
}
